version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: flamingo
      POSTGRES_PASSWORD: zeremi
    # volumes:
    #   # Pour lancer un dump automatiquement au montage du conteneur
    #   - ./app/database/dump.sql:/docker-entrypoint-initdb.d/database.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
